comment: Sources ajoutées automatiquement à chaque lancement.
flux:
- id: dec-wiki-openstreetmap-org
  nom: OpenStreetMap Wiki
  url: https://wiki.openstreetmap.org/w/index.php?title=Special:RecentChanges&feed=atom
  site: https://wiki.openstreetmap.org/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-peertube-openstreetmap-fr
  nom: peertube.openstreetmap.fr
  url: https://peertube.openstreetmap.fr/feeds/videos.xml
  site: https://peertube.openstreetmap.fr/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-toolbox-hotosm-org
  nom: HOT Toolbox
  url: https://toolbox.hotosm.org/index.xml
  site: https://toolbox.hotosm.org/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-boutique-brgm-fr
  nom: boutique.brgm.fr
  url: https://boutique.brgm.fr/rss.xml
  site: https://boutique.brgm.fr/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-assistance-brgm-fr
  nom: BRGM
  url: https://assistance.brgm.fr/rss.xml
  site: https://assistance.brgm.fr/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-dpsm-brgm-fr
  nom: BRGM
  url: https://dpsm.brgm.fr/rss.xml
  site: https://dpsm.brgm.fr/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-maniaques-fr
  nom: maniaques.fr
  url: https://maniaques.fr/feed/
  site: https://maniaques.fr/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-geoweeknews-com
  nom: Geo Week News
  url: https://www.geoweeknews.com/feed/
  site: https://geoweeknews.com/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-estrepublicain-fr
  nom: L'Est Républicain
  url: https://estrepublicain.fr/rss
  site: https://estrepublicain.fr/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-missingmaps-org
  nom: Missing Maps
  url: https://missingmaps.org/feed.xml
  site: https://missingmaps.org/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-prev-openstreetmap-fr
  nom: prev.openstreetmap.fr
  url: https://prev.openstreetmap.fr/rss
  site: https://prev.openstreetmap.fr/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-notebookcheck-biz
  nom: Notebookcheck.fr
  url: https://www.notebookcheck.biz/index.php?id=20501
  site: https://notebookcheck.biz/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-rapport-activite-brgm-fr
  nom: BRGM
  url: https://rapport-activite.brgm.fr/rss.xml
  site: https://rapport-activite.brgm.fr/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-architectes-org
  nom: Ordre des architectes
  url: https://architectes.org/rss.xml
  site: https://architectes.org/
  filtre: mots_cles
  decouverte: '2026-09-23'
- id: dec-help-openstreetmap-org
  nom: OpenStreetMap
  url: https://help.openstreetmap.org/index.xml
  site: https://help.openstreetmap.org/
  filtre: mots_cles
  decouverte: '2026-09-23'
